[package]
name = "kvwrap-bin"
description = "Binary crate for kvwrap gRPC server"
readme = "README.md"

publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "kvwrap"
path = "src/main.rs"

[dependencies]
kvwrap = { workspace = true, features = ["distributed", "sled"] }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
fracturedjson = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[package.metadata.dist]
dist = true